# Header
menu:
  Home: /
  Archives: /archives
  Projects: /projects
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-39994684-2
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
